# Generated by Django 4.2.16 on 2024-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily rental fee for the book",
                        max_digits=8,
                    ),
                ),
                (
                    "inventory",
                    models.PositiveIntegerField(help_text="Number of copies available"),
                ),
                (
                    "cover",
                    models.CharField(
                        choices=[("1", "SOFT"), ("2", "HARD")],
                        help_text="Type of book cover",
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.CharField(help_text="Author of the book", max_length=255),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the book", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
